# Generated by Django 3.0.8 on 2020-12-28 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue1', models.IntegerField()),
                ('clue2', models.IntegerField()),
                ('clue3', models.IntegerField()),
                ('clue4', models.IntegerField()),
                ('clue5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('round1', models.IntegerField()),
                ('round2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('state', models.CharField(choices=[('O', 'Open'), ('S', 'Started'), ('C', 'Completed')], default='O', max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block1', models.IntegerField()),
                ('block2', models.IntegerField()),
                ('block3', models.IntegerField()),
                ('block4', models.IntegerField()),
                ('block5', models.IntegerField()),
                ('double_trouble1', models.CharField(max_length=5)),
                ('double_trouble2', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField()),
                ('answer', models.TextField()),
                ('link_question', models.TextField(blank=True)),
                ('link_answer', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('state', models.CharField(choices=[('C', 'Covered'), ('U', 'Uncovered'), ('A', 'Answered')], default='C', max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='game.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('submission', models.TextField()),
                ('value', models.IntegerField(null=True)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='game.Clue')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.Player')),
            ],
        ),
    ]
