# Generated by Django 3.0.8 on 2020-12-26 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
